export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const CREAR_COLEGIO = "CREAR_COLEGIO";
export const EDITAR_COLEGIO = "EDITAR_COLEGIO";
export const ELIMINAR_COLEGIO = "ELIMINAR_COLEGIO";
export const OBTENER_COLEGIO = "OBTENER_COLEGIO";
export const OBTENER_METODOLOGIA = "OBTENER_METODOLOGIA";

//types de aliado

export const GET_INFO_ALIADO = "GET_INFO_ALIADO";
export const ACTUALIZAR_INFO_ALIADO = "ACTUALIZAR_INFO_ALIADO"
export const ELIMINAR_ALIADO = "ELIMINAR_ALIADO";

